spring.application.name=url-shortener-sb

spring.datasource.url=jdbc:mysql://url-shortner-ak-url-shortner-ak.e.aivencloud.com:25225/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


jwt.secret=E98v/kVP+7ADWEd1FCN8w2U9Jg31tJ+4+bownoXlCT8=
jwt.expiration=172800000


logging.level.org.springframework.security=DEBUG
logging.level.org.url.shortener=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework=DEBUG
logging.level.org.springframework.web.servlet=TRACE

frontend.url=http://localhost:5173
# frontend.url=${FRONTEND_URL:http://localhost:5173}

#Local host config
# spring.datasource.url=jdbc:mysql://localhost:3306/urlshortenerdb
# spring.datasource.username=root
# spring.datasource.password=your_password